name: Run Script

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pip Installer
  # You may pin to the exact commit or the version.
  # uses: BSFishy/pip-action@8f2d471d809dc20b6ada98c91910b6ae6243f318
        uses: BSFishy/pip-action@v1
        with:
          # The packages to install from Pip
          packages: requests
      - name: setup python
        uses: actions/setup-python@v2
        with:
           python-version: 3.8 #install the python needed
      - name: execute py script # run the run.py to get the latest data
        run: |
           python generate.py
